### ISSUE TITLE
sort player list by player name if event hasn't started

### ISSUE THREAD

**Issue by boada** [powens/40kbot#15]
I've not run this code (i don't have a bcp api key) but a possible solution could be:

changing [line 124](https://github.com/powens/40kbot/blob/8483a0ebf54d35949d326e3e1ce9689c56c81a06/backend/server.py#L124) to something like: 

``` 
players = sorted(
        players,
        key=lambda x: (x.get("numWins", 0), x.get("battlePoints", 0), x.get("LastName", 0), x.get("FirstName", 0)),
        reverse=True,
    )
```

that might reverse sort the names though. might have to have two different sort blocks with an `if/else` statement for when the event has or hasn't started.

another possible (maybe better?) initial sorting solution would be to also group the (sub)factions together.

**Comment by powens** [comment]
Sounds good to me! I've been busy with some other projects lately, but I definitely need to work out all the bugs (and finish the new SPA version eventually).

I'll make the adjustments later tonight.
