### ISSUE TITLE
wrong faction

### ISSUE THREAD

**Issue by boada** [powens/40kbot#17]
shown as iron hands. army list is knights.

https://listbot40k.herokuapp.com/event_list/W6D4EWFQ9J

**Comment by boada** [comment]
it's probably an issue with the bcp data. but just in case. 😉

**Comment by powens** [comment]
![371E081E-A05D-4D01-A7E6-88C5F964C987](https://user-images.githubusercontent.com/1919554/227609040-3746bd17-4814-41e7-b1ba-5479a47a1193.jpeg)

Yeah, definitely a player input/bcp data quality issue. Closing the issue
